name: Java CI on Automacao Test Software

on: [ push ]

jobs:
  build_web_app:
    name: build web app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: leonidesfernando/teste-software
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots compile

  start_and_stop_web_app:
    name: Start
    runs-on: ubuntu-latest
    needs: [ build_web_app ]
    ports:
      - 8080: 8080
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
      - name: Run the Maven to start the webapp
        run: mvn spring-boot:run

      - name: curl
        uses: wei/curl@v1
        with:
          args: -X POST localhost:35729/actuator/shutdown
          #stop_web_app:
          #name: Stop
          #runs-on: ubuntu-latest
          #needs: [ build_web_app, start_web_app ]
          #steps:
          #- name: curl
          #uses: wei/curl@v1
          #with:
          #args: -X POST http://localhost:8080/actuator/shutdown